version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    container_name: backend-app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: frontend-app
